hyperparameter:
  seed: 0
  lr: 0.001
  batch_size: 64
  schedular:
    plateau:
      mode: "min"
      factor: 0.5
      patience: 3
  
tictactoe:
  game_net:
    init_method: "he"
    conv_config:
      out_channel: 64
      kernel_size: 3
    residual_config:
      n_block: 3
      # mid_channel: 32
      kernel_size: 3
    policy_value_config:
      p_channel: 32
      v_channel: 32
      v_middle: 64
      v_dropout: 0.15
  n_iteration: 15
  n_process: 8
  n_game: 100
  n_simulation: 100
  n_epoch: 10
  battle_version: 7
  model_in_version: 0
  model_out_version: 1
  eval_model_version: 0
  battle_format: "data/{game}/battle_v{version}.pt"
  model_format: "data/{game}/model_v{version}.pt"
