hyperparameter:
  seed: 0
  lr: 0.05
  batch_size: 32
  schedular:
    plateau:
      mode: "min"
      factor: 0.8
      patience: 5
  
tictactoe:
  game_net:
    init_method: "xaiver"
    conv_config:
      out_channel: 32
      kernel_size: 3
    residual_config:
      n_block: 2
      out_channel: 32
      kernel_size: 3
    policy_value_config:
      p_channel: 2
      v_channel: 1
      v_middle: 72
  n_iteration: 5
  n_process: 8
  n_game: 50
  n_simulation: 25
  n_epoch: 50
  battle_version: 0
  model_in_version: 0
  model_out_version: 1
  battle_format: "data/{game}/battle_v{version}.pt"
  model_format: "data/{game}/model_v{version}.pt"