board_shape: [1, 3, 6, 7]  # batch x channel x height x width

game_net:
  init_method: "he"
  conv_config:
    out_channel: 128
    kernel_size: 3
  residual_config:
    n_block: 5
    kernel_size: 3
  policy_value_config:
    action_space: 7  # 7 columns, not 6*7=42
    p_channel: 32
    v_channel: 32
    v_middle: 128
    v_dropout: 0.15

n_iteration: 20
n_process: 8
n_game: 50
n_simulation: 200
n_epoch: 15
battle_version: 0
model_in_version: 0
model_out_version: 1
battle_format: "data/{game}/battle_v{version}.pt"
model_format: "data/{game}/model_v{version}.pt"
